- name: Create volume
  dellemc.unity.volume:
    unispherehost: "{{ unispherehost }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    vol_name: "{{ vol_name }}"
    pool_name: pool0
    size: 2
    is_thin: true
    compression: true
    advanced_dedup: true
    state: present
