---
- name: Get info of all volumes
  ansible.builtin.import_tasks: get_info_volumes.yml
  when: user_input == "1"
- name: Create a volume
  ansible.builtin.import_tasks: create_volume.yml
  when: user_input == "2"
- name: Rename a volume; Modify a volume
  ansible.builtin.import_tasks: rename_volume.yml
  when: user_input == "3"
- name: Delete a volume
  ansible.builtin.import_tasks: delete_volume.yml
  when: user_input == "4"

