- name: Manage Unity
  hosts: unity
  connection: local
  gather_facts: false
  become: true
  vars:
    ansible_python_interpreter: /ansible/unity_venv/bin/python3

  vars_prompt:
    - name: user_input
      prompt: |
        Please select an action:
        1. Get list of FileSystems names and ids
        2. Create a FileSystem
        3. Rename a FileSystem
        4. Delete a FileSystem
      private: false
    - name: "FS_name"
      prompt: "Enter the Filesystem name that you want to create"
      private: false
    - name: "Nas_name"
      prompt: "Enter the NAS server name for the new filesystem"


  tasks:
    - name: Include unity_configuration role
      ansible.builtin.include_role:
        name: unity_FileSystem_management
